### ISSUE TITLE
Expand universal links handler with ENS name + update page styling

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/universal-links-handler#17]
# Problem
When inviting people to Status, users are presented with a web2 page that shows the chat key. For many people this will be their first encounter with Status and we want to make this experience as approachable (web2 familiarity) as possible. The current representation of the chat key can be intimidating.

## Current behavior

- url and page show chat key: https://get.status.im/user/0x04f1ab965a3db6433923ceba0488ff605f230aca4c4c93bb6563c10b700cfdbbed2a364c980b9cf9679f352584d4da44cc01fc1e7257f1d2b80ffff5af64aa129f
- Download Status button is easily overlookedd because of its styling and position. (esp. on desktop)

![Screenshot_20200113-120812_Firefox](https://user-images.githubusercontent.com/35233054/72253046-eea65700-3600-11ea-988f-6ab352322c66.jpg)

## Expected behavior
According to designs on Figma: https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4066%3A6653

![Frame 26](https://user-images.githubusercontent.com/35233054/72253029-e0583b00-3600-11ea-8b8a-b0e765cbf686.png)

1. User A shares profile
2. If user A has ENS name (that's set to show in chat), link _generated_ by Status includes ENS name instead of chat key. If user A has random name, url includes chat key as is
3. If user A has ENS name, url _shown_ in browser includes ENS name get.status.im/user/ensname instead of chat key. If user A has random name, url includes chat key as is
4. If user A has ENS name get.status.im/user/ensname shows ENS name to _view_ and _copy_. If user A has random name, get.status.im/user/ensname shows shows random name the _view_ and chat key to _copy_
7. If user B has Status installed, url _triggers_ native dialog to open url in Status

## Implementation
- Generate url in Status, depending on whether user has ENS name (in status-react) > @Ferossgp 
- Derive ENS name from url and display in updated get.status.im/user/username designs > @nistorchristian
- Generate random name from Chat key to display in updated get.status.im/user/username designs > @nistorchristian

@jakubgs can you add the Go library for random name generation in the front end here? And please give Christian access to this repo 🙏

**Comment by hesterbruikman** [comment]
cc @rachelhamlin @j-zerah and @errorists (for clarification on designs if needed)

@nestorchristian one thing we did not discuss is behavior if the user opens the url on mobile and has Status installed. Point 5 in the issue above. Can you investigate what would be required for that on iOS and Android?

**Comment by jakubgs** [comment]
The Chat names (3-word names) are generated in `status-go` here:
https://github.com/status-im/status-go/tree/develop/protocol/identity/alias
We normally use it via [`GenerateFromPublicKeyString()`](https://github.com/status-im/status-go/blob/330d177de6554eee61a85d9eff7582c99fbbfcad/protocol/identity/alias/generate.go#L32).
Implementation is from what I can see an simplified [Linear-feedback shift register](https://en.wikipedia.org/wiki/Linear-feedback_shift_register) and was done by @cammellos.

I found this [lfsr](https://www.npmjs.com/package/lfsr) JS package but it seems more complex than what we use. @cammellos can you verify that you simplified the algorithm for the Go implementation?

The sensible thing to do would be probably to create a separate library at(for example):
https://github.com/status-im/js-chat-name-gen
which implements only the Chat name generation from Chat key, and use that on the page.

**Comment by errorists** [comment]
thanks! probably the only read clarification I can give is on responsiveness of those. 
that container holding all data should take a percentage value of the screen width up to a maximum width of 400px above which it doesn't grow, only keeps its centred position. 
Below that value, right and left margins should be kept at around 12.5% of screen width, so the container is at around 75%. Vertically it's also centred in the screen, minimum top and bottom margins should be at 64px. 
The top navigation bar should be shared with the product page, status.im so does the black footer. The height of the container holding the top bar navigation and the user data container, should be at least 100vh or 100% screen height, so the footer begins directly below screen fold, unless the data container is higher than screen height.

**Comment by errorists** [comment]
also it would be cool if we could keep all of that JS shit to minimum and keep it lean, this should load as fast as possible 🙏 

<img width="949" alt="Screenshot 2020-01-13 at 13 03 30" src="https://user-images.githubusercontent.com/4932774/72254718-2ca57a00-3605-11ea-966a-86c3d6bccd67.png">

**Comment by jakubgs** [comment]
I've created a JS library for converting Chat keys to Chat names:
https://github.com/status-im/js-status-chat-name
This should let us display the 3-word Chat name with the `get.status.im` contact page.

**Comment by j-zerah** [comment]
@rachelhamlin @andremedeiros maybe you guys know how we can fix the universal links page. There are two issues @NistorCristian is unable to fix:

1. Scanning QR code from https://get.status.im/user/hester in Status New chat results in error 'Unable to read code Please enter or scan a valid chat key or username'

2. Download button should eventually be contextually dependent on whether Status is installed. For the time being this should go to https://status.im/get/

How can we detect if Status is installed?

cc @hesterbruikman

**Comment by errorists** [comment]
> How can we detect if Status is installed? 

while I can't answer that, I can add that I designed that functionality based on what Snapchat does with their profile urls. if I open that link in safari it would ask me first if I want to go ahead and open it in the app. 

![IMG_1323](https://user-images.githubusercontent.com/4932774/74180342-a26e2700-4c3f-11ea-878d-e7797df069f2.jpeg)

if I decline, it would then go ahead and place a banner in browser's toolbar allowing to jump to app at any time. this works as long as I have the app installed

![IMG_1324](https://user-images.githubusercontent.com/4932774/74180352-a601ae00-4c3f-11ea-84f7-3c595926bd5c.jpeg)

**Comment by jakubgs** [comment]
I can take a look at #1, I don't think #2 can be solved without modifying the App, at least for Android:
https://stackoverflow.com/a/12901352
Not sure about iOS.

**Comment by jakubgs** [comment]
Here are some related issues and PRs:

* https://github.com/status-im/status-react/issues/7651
* https://github.com/status-im/status-react/pull/9811

It seems like it was merged and tested according to @Serhy but it doesn't work anymore.

**Comment by jakubgs** [comment]
I have verified with [the PR build] from https://github.com/status-im/status-react/pull/9811 that the QR codes it accepts are just usernames, like `hester`, not URLs, like `status-im://user/hester`. But what's weird is that doesn't work in the RC12 or the nightly build. It just considers everything an invalid contact unless it's a direct chat key like so:
https://get.status.im/user/0x0461f576da67dc0bca9888cdb4cb28c80285b756b324109da94a081585ed6f007cf00afede6b3ee5638593674fee100b590318fc7bdb0054b8dd9445acea216ad2

This looks like some kind of regression. Also, we should respect both formats of QR codes.

**Comment by jakubgs** [comment]
I implemented converting chat keys to chat names in https://github.com/status-im/universal-links-handler/pull/22.

**Comment by hesterbruikman** [comment]
@errorists @jakubgs I'll close this issue as we now have smaller issues to refine:
- Small update to white background height https://github.com/status-im/universal-links-handler/issues/23
- Dynamic page depending on whether Status is installed (issue to be added)
- Link Invite friends in Core app to join.status.im/user/... https://github.com/status-im/status-react/issues/10028
- Fix QR code reading in Status when viewing QR code for ENS name join.status.im/user/hester https://github.com/status-im/status-react/issues/10017
