### ISSUE TITLE
Weird styling of contact page

### ISSUE THREAD

**Issue by jakubgs** [status-im/universal-links-handler#20]
I've deployed the changes from #19 and it looks kinda weird:

![get_status_im_update](https://user-images.githubusercontent.com/2212681/74147982-a92b7880-4c04-11ea-9e57-3949f11a50a1.png)

https://get.status.im/user/0x04e139115a1acc72510388fcf7e1cf492784c9a839888b25271465f4f1baa38c2d3997f8fd78828eb8628bc3bb55ababd884c6002d18330d59c404cc9ce3e4fb35

@hesterbruikman @NistorCristian

**Comment by hesterbruikman** [comment]
Noticing a few issues here:

- Scanning QR code from https://get.status.im/user/hester in Status `New chat` results in error 'Unable to read code Please enter or scan a valid chat key or username'
- Copy copies the full text, intention is to copy only the ENS name or chat key
- Download button should eventually be contextually dependent on whether Status is installed. For the time being this should go to https://status.im/get/
- There's a lot of unnecessary javascript as @errorists raised [here ](https://github.com/status-im/universal-links-handler/issues/17#issuecomment-573631450) top navigation and footer would ideally be shared with the main domain and not loaded again.

**Comment by jakubgs** [comment]
I've reverted the https://get.status.im/ page to 9b181a20e97e8ddb5e6ad389eba0f719b64de6c7.h

**Comment by errorists** [comment]
another thing that needs addressing
• Both the Header and subtitle in the box below QR, should only say the username without the entire view user profile in Status string. so instead of `View user hester profile in Status` it should rather say `hester` or `0x041…2f20`
The same with text string below the button too. All of them have the same bs text string instead of just the actual username/key.

**Comment by jakubgs** [comment]
I've deployed changes from #21 and it looks good now.

![get_status_style_fix](https://user-images.githubusercontent.com/2212681/74185138-57a4dd00-4c48-11ea-8061-2a9005844eb9.png)

I also increased QR code resolution in 9f9be817b8e8973d31998a705ed11d2989a82a14 because it looked too fuzzy.

**Comment by hesterbruikman** [comment]
Awesome @jakubgs ! Looks good now!
One last check. Does the QR code work for you when your ENS name is included?
