### ISSUE TITLE
Add invite code to QR

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/universal-links-handler#50]
## User story
As recipient of a referral url I want to scan the invite because a QR is shown when I open the invite url and expect to be able to use it

## Issue
QR code does not seem to pass invite code of a invite url created through the referral service

This concerns any join.status.im url that is appended with an invite code
- chat key
- ENS name
- advertiser url
- dapp url

### Current
- Scan QR code
- Tap `Open in Status`
- Download and Install
- Chat with referrer and request to Accept Starter Pack and Referral bonus attribution not visible

### Expected
- Scan QR code
- Tap `Open in Status`
- Download and Install
- Chat with referrer and request to Accept Starter Pack and Referral bonus attribution visible

**Comment by jakubgs** [comment]
I'm not sure what you're referring to. I tried the following URLs:

* https://join.status.im/u/jakubgs.eth?invite=dsadasdasdasdasdasdasdasdasdas
* https://join.status.im/status?invite=dsadasdasdasdasdasdasdasdasdas
* http://localhost:3000/g/args?a=0x0461f576da67dc0bca9888cdb4cb28c80285b756b324109da94a081585ed6f007cf00afede6b3ee5638593674fee100b590318fc7bdb0054b8dd9445acea216ad2&a2=75d9c09b-0d6f-4494-b7da-7bb1e35b1728-0x04f1ab965a3db6433923ceba0488ff605f230aca4c4c93bb6563c10b700cfdbbed2a364c980b9cf9679f352584d4da44cc01fc1e7257f1d2b80ffff5af64aa129f&a1=whatever&invite=dasdasdasdasdasdasdasdasdasdas

And I see all of them including the `invite` URL argument.

**Comment by jakubgs** [comment]
Oh, I see, it's not handled for the public key:

https://join.status.im/u/0x0481d914d869332867c1e631996f7a10e765f8b9245efbe05b5e4d3c2bc2091760bf656d5e031d2e7838c575949b025b35f16edaa74a088ea7f367a61c60db7fc7?invite=dsadasdasdasdasdasdasdasdasdas

That should be simple.
