### ISSUE TITLE
QR image broken on Android

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/universal-links-handler#59]
## Problem
QR image shows as 'Invalid data' (status 400 Bad request) when opened on Android
Occurs for public chats, ENS name, Chat key, Group chat, dapps

### Current
![Screenshot_2020-12-28 Join hester in Status](https://user-images.githubusercontent.com/35233054/103228008-197fdd00-4930-11eb-986c-5595ad5cf258.png)

### Expected
![Screenshot_2020-12-28 Join hester in Status(1)](https://user-images.githubusercontent.com/35233054/103228041-2f8d9d80-4930-11eb-9c3f-5410aa72f10d.png)

#### OS
Android

#### Browsers
Chrome
Firefox
Brave
Opera

### Note
No issues on Safari on iOS

**Comment by jakubgs** [comment]
Nice, only now noticed this, because nobody pinged me.

**Comment by jakubgs** [comment]
This is the code responsible for generating the QR code:
https://github.com/status-im/universal-links-handler/blob/9bacef74cd5ef0c404c7af9250467d94c0886434/routes/index.js#L189-L198

**Comment by jakubgs** [comment]
This us how the QR code URL looks like normally:
![image](https://user-images.githubusercontent.com/2212681/126770392-c6ef7702-feab-4153-acf6-c7d12112d2e7.png)

And this is is what I see with an attached debug console to my tablet:
![image](https://user-images.githubusercontent.com/2212681/126770481-f2b598d7-715e-4b33-8f97-861dea7b2710.png)

Clearly the URL starts with `status-im://` expected by android, but not parseable by the QR HTTP endpoint.

**Comment by jakubgs** [comment]
Now, one question would be, should the QR code on Android be a `status-im://` one or a `https://` one...

**Comment by jakubgs** [comment]
Arguably the `https://` one makes more sense because someone might want to show it from their device to someone else.

**Comment by jakubgs** [comment]
I've implemented and deployed a fix that makes it use `https://` in the QR code on Android: https://github.com/status-im/universal-links-handler/commit/cadf83ef

@qoqobolo can you confirm that it works as expected?

**Comment by qoqobolo** [comment]
Works great now, thanks @jakubgs !

**Comment by jakubgs** [comment]
Thanks.
